// 单页面板，内嵌不外链。前端代码刻意不用模板字符串，避免和这里的拼接打架。
export function renderHTML({ port }) {
  return '<!doctype html><html lang="zh"><head><meta charset="utf-8">' +
    '<meta name="viewport" content="width=device-width,initial-scale=1">' +
    '<title>agentdesk</title><style>' + CSS + '</style></head><body>' + BODY +
    '<script>' + JS + '</script></body></html>';
}

const CSS = [
  ':root{--bg:#fbfbfd;--card:#fff;--fg:#18181b;--dim:#71717a;--line:#e4e4e7;--shadow:0 1px 3px rgba(0,0,0,.06)}',
  '@media(prefers-color-scheme:dark){:root{--bg:#0b0b0e;--card:#16161a;--fg:#f4f4f5;--dim:#8b8b95;--line:#26262c;--shadow:none}}',
  '*{box-sizing:border-box;margin:0;padding:0}',
  'body{background:var(--bg);color:var(--fg);font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;padding:24px;max-width:820px;margin:0 auto}',
  'header{display:flex;align-items:center;gap:12px;margin-bottom:20px}',
  'h1{font-size:15px;font-weight:600;letter-spacing:.3px}',
  '#count{font-size:12px;color:var(--dim);margin-right:auto}',
  'button{font:inherit;font-size:12px;padding:6px 12px;border:1px solid var(--line);background:var(--card);color:var(--fg);border-radius:7px;cursor:pointer}',
  'button:hover{border-color:var(--dim)}',
  'button.on{background:#3b82f6;border-color:#3b82f6;color:#fff}',
  '.task{background:var(--card);border:1px solid var(--line);border-left:3px solid var(--bar);border-radius:9px;padding:13px 15px;margin-bottom:9px;box-shadow:var(--shadow);display:flex;gap:13px;align-items:flex-start}',
  '.badge{flex:none;display:inline-flex;align-items:center;gap:5px;font-size:12px;font-weight:600;color:var(--bar);background:color-mix(in srgb,var(--bar) 12%,transparent);padding:4px 9px;border-radius:6px;white-space:nowrap}',
  '.main{min-width:0;flex:1}',
  '.title{font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.summary{color:var(--dim);font-size:13px;margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  '.meta{color:var(--dim);font-size:12px;margin-top:6px;display:flex;gap:10px;flex-wrap:wrap}',
  '.meta code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;background:var(--bg);padding:1px 5px;border-radius:4px}',
  '.guess{opacity:.65}',
  '.task{cursor:default}',
  '.task.unread{cursor:pointer;background:linear-gradient(90deg,color-mix(in srgb,var(--bar) 7%,var(--card)),var(--card) 60%)}',
  '.dot{width:7px;height:7px;border-radius:50%;background:var(--bar);flex:none;margin-top:6px}',
  '.task:not(.unread) .dot{background:transparent}',
  '#allseen{display:none}',
  '#fold{display:none}',
  // 只有跑在悬浮窗里才有壳可以缩，浏览器里不显示这个按钮
  'body.compact.shell #fold{display:inline-block;padding:2px 8px}',
  'body.compact.folded #list{display:none}',
  'body.compact.folded header{border-bottom:0}',
  '.empty{text-align:center;color:var(--dim);padding:60px 20px;font-size:13px}',
  '.pulse{animation:p 2s ease-in-out infinite}@keyframes p{50%{opacity:.45}}',
  // 紧凑模式是另一种排版，不是把大面板等比缩小：
  // 340px 宽放不下卡片那套留白，改成清单 —— 细分隔线、单行标题、右对齐时间。
  'body.compact{padding:0;max-width:none;background:var(--bg)}',
  'body.compact header{position:sticky;top:0;z-index:2;margin:0;padding:9px 12px;',
  '  background:var(--bg);border-bottom:1px solid var(--line);gap:8px}',
  'body.compact h1{font-size:11.5px;letter-spacing:.2px}',
  'body.compact #count{font-size:10.5px}',
  'body.compact button{font-size:10.5px;padding:2px 7px;border-radius:5px;white-space:nowrap;flex:none}',
  'body.compact header{flex-wrap:nowrap}',
  'body.compact #count{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  'body.compact #perm,body.compact #try{display:none}',
  'body.compact #list{padding:0}',
  // 清单行：无卡片、无左边框，只有一条细分隔线
  'body.compact .task{display:grid;grid-template-columns:auto 1fr auto;align-items:baseline;',
  '  gap:7px;padding:8px 12px;margin:0;border:0;border-radius:0;box-shadow:none;',
  '  border-bottom:1px solid var(--line);background:var(--card)}',
  'body.compact .task:last-of-type{border-bottom:0}',
  'body.compact .task.unread .title::before{content:"";display:inline-block;width:5px;height:5px;',
  '  border-radius:50%;background:var(--bar);margin-right:6px;vertical-align:middle;',
  '  position:relative;top:-1px}',
  'body.compact .task:not(.unread) .title{font-weight:500;color:var(--dim)}',
  'body.compact .task:not(.unread) .badge{opacity:.5}',
  // 两组之间给一条实的分界，别让"在跑的"和"跑完的"糊成一片
  'body.compact .task.groupstart{border-top:6px solid var(--bg);margin-top:-1px}',
  'body.compact .badge{background:none;padding:0;font-size:11px;color:var(--bar);',
  '  line-height:1.4;width:14px;text-align:center;flex:none}',
  'body.compact .dot{display:none}',
  'body.compact .main{grid-column:2;min-width:0}',
  'body.compact .title{font-size:12.5px;font-weight:600;line-height:1.35}',
  'body.compact .sub{font-size:10.5px;color:var(--dim);margin-top:2px;',
  '  overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
  'body.compact .who{color:var(--fg);opacity:.75;font-weight:600;',
  '  font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:9.5px;',
  '  letter-spacing:.2px;margin-right:2px}',
  'body.compact .when{grid-column:3;font-size:10px;color:var(--dim);white-space:nowrap}',
  'body.compact .empty{padding:40px 16px;font-size:11.5px}',
  'body.compact button.more{border:0;border-top:1px solid var(--line);border-radius:0;',
  '  padding:8px;background:var(--bg)}',
].join('');

const BODY = [
  '<header><h1>agentdesk</h1><span id="count"></span>',
  '<button id="perm">开启通知</button>',
  '<button id="try" title="绕过服务端，直接由页面发一条通知">试一条</button>',
  '<button id="mute" title="有 agent 等你时响一声">🔔</button>',
  '<button id="allseen" title="把所有已完成标记为看过">全部已读</button>',
  '<button id="fold" title="收起 / 展开">▾</button></header>',
  '<div id="list"></div>',
].join('');

const JS = [
  'var STATES={},ATT=[],granted=false,FG=[],BUILD=null;',
  'var COMPACT=/[?&]compact=1/.test(location.search);',
  'if(COMPACT){document.body.className="compact";',
  '  document.getElementById("allseen").textContent="已读";',
  '  document.getElementById("mute").title="有 agent 等你时响一声";}',
  'var permBtn=document.getElementById("perm");',
  'function syncPerm(){',
  '  granted = ("Notification" in window) && Notification.permission==="granted";',
  '  permBtn.textContent = granted ? "通知已开启" : "开启通知";',
  '  permBtn.className = granted ? "on" : "";',
  '}',
  'permBtn.onclick=function(){ if(!("Notification" in window)) return alert("此浏览器不支持通知");',
  '  Notification.requestPermission().then(syncPerm); };',
  'syncPerm();',
  'var actx=null, muted=localStorage.getItem("ad_muted")==="1";',
  'var muteBtn=document.getElementById("mute");',
  'function syncMute(){muteBtn.textContent=muted?"🔕":"🔔";muteBtn.className=muted?"":"on";}',
  'muteBtn.onclick=function(){muted=!muted;localStorage.setItem("ad_muted",muted?"1":"0");syncMute();if(!muted)beep([880,1174]);};',
  'syncMute();',
  // 浏览器要求用户先与页面交互过才允许出声，所以任何一次点击都顺手把音频上下文激活
  'document.addEventListener("click",function(){',
  '  try{ if(!actx) actx=new (window.AudioContext||window.webkitAudioContext)();',
  '       if(actx.state==="suspended") actx.resume(); }catch(e){}',
  '});',
  // 系统通知可能被 OS 静默拦掉，声音不会 —— 不需要权限，跨平台行为一致
  'function beep(freqs){',
  '  if(muted) return;',
  '  try{',
  '    if(!actx) actx=new (window.AudioContext||window.webkitAudioContext)();',
  '    if(actx.state==="suspended") actx.resume();',
  '    freqs.forEach(function(hz,i){',
  '      var o=actx.createOscillator(), g=actx.createGain();',
  '      o.connect(g); g.connect(actx.destination);',
  '      o.type="sine"; o.frequency.value=hz;',
  '      var t0=actx.currentTime+i*0.16;',
  '      g.gain.setValueAtTime(0,t0);',
  '      g.gain.linearRampToValueAtTime(0.18,t0+0.012);',
  '      g.gain.exponentialRampToValueAtTime(0.0008,t0+0.14);',
  '      o.start(t0); o.stop(t0+0.15);',
  '    });',
  '  }catch(e){}',
  '}',
  // 二分法用：不经过 SSE、不经过服务端。能弹说明问题在事件推送，不能弹就是浏览器/系统层面
  'document.getElementById("try").onclick=function(){',
  '  beep([880,1174]);',
  '  if(!("Notification" in window)) return alert("此浏览器不支持通知 API");',
  '  if(Notification.permission!=="granted")',
  '    return alert("当前权限: "+Notification.permission+" —— 先点左边「开启通知」");',
  '  try{',
  '    var n=new Notification("⏸ 等你 · 通知自检",{',
  '      body:"这条是页面直接发的，没走服务端。\\n看到它说明浏览器和系统都正常。",',
  '      requireInteraction:true});',
  '    n.onclick=function(){window.focus();n.close();};',
  '  }catch(e){alert("发送失败: "+e.message);}',
  '};',

  'function ageShort(ms){var s=Math.floor(ms/1000);if(s<60)return s+"秒";',
  '  var m=Math.floor(s/60);if(m<60)return m+"分";',
  '  var h=Math.floor(m/60);return h<24?h+"时":Math.floor(h/24)+"天";}',
  'function age(ms){var s=Math.floor(ms/1000);if(s<60)return s+" 秒";',
  '  var m=Math.floor(s/60);if(m<60)return m+" 分钟";',
  '  var h=Math.floor(m/60);return h<24?h+" 小时":Math.floor(h/24)+" 天";}',
  'function shortCwd(p){if(!p)return "";var a=p.split(/[/\\\\]/).filter(Boolean);return a.slice(-2).join("/");}',
  'function esc(s){return String(s==null?"":s).replace(/[&<>"]/g,function(c){',
  '  return {"&":"&amp;","<":"&lt;",">":"&gt;","\\"":"&quot;"}[c];});}',

  'function setFavicon(color,n){',
  '  var c=document.createElement("canvas");c.width=c.height=64;var x=c.getContext("2d");',
  '  x.fillStyle=color;x.beginPath();x.arc(32,32,30,0,Math.PI*2);x.fill();',
  '  if(n){x.fillStyle="#fff";x.font="bold 42px -apple-system,sans-serif";x.textAlign="center";',
  '    x.textBaseline="middle";x.fillText(String(n),32,35);}',
  '  var l=document.querySelector("link[rel=icon]");',
  '  if(!l){l=document.createElement("link");l.rel="icon";document.head.appendChild(l);}',
  '  l.href=c.toDataURL();}',

  'function render(tasks){',
  '  var list=document.getElementById("list");',
  '  if(!tasks.length){list.innerHTML="<div class=empty>还没有任何任务事件<br><br>跑一次 agentdesk init 接入你的 agent</div>";',
  '    document.title="agentdesk";setFavicon("#71717a",0);',
  '    document.getElementById("count").textContent="";return;}',
  '  var need=tasks.filter(function(t){return t.needs;});',
  '  var now=Date.now();',
  // 主列表只放"当前的"：进行中的一律显示，已结束的只留最近 RECENT_MS。
  // 更早的收进折叠区 —— 包括没看过的，那些不能丢，但也不该挤占当前视图。
  '  var RECENT_MS=6*3600*1000;',
  '  var shown=[],hidden=0,hiddenUnread=0,firstDone=null;',
  '  tasks.forEach(function(t){',
  '    var active = ["waiting","running","bgrun"].indexOf(t.state)>=0;',
  '    var recent = (now - t.last_seen) < RECENT_MS;',
  '    if(!window.__expanded && !active && !recent){',
  '      hidden++; if(t.seen===false) hiddenUnread++; return;',
  '    }',
  '    if(!active && firstDone===null) firstDone=t.id;',
  '    shown.push(t);});',
  '  list.innerHTML=shown.map(function(t){',
  '    var st=STATES[t.state]||{label:t.state,icon:"?",color:"#71717a"};',
  '    var guess = t.confidence==="guess";',
  '    var bgN = t.bg ? Object.keys(t.bg).length : 0;',
  '    var unread = t.seen===false;',
  '    if(COMPACT){',
  '      var bits=[]; if(bgN) bits.push("⧗ "+bgN+" 个后台");',
  '      if(t.summary||t.prompt) bits.push(t.summary||t.prompt);',
  '      var sub = "<span class=who>"+esc(t.agent)+"</span>" + (bits.length? " "+esc(bits.join(" · ")) : "");',
  '      return "<div class=\\"task"+(unread?" unread":"")+(t.id===firstDone?" groupstart":"")+"\\" data-id=\\""+esc(t.id)+"\\" style=\\"--bar:"+st.color+"\\">"+',
  // 紧凑模式只有符号没有文字，鼠标停上去得能看出是什么状态
  '        "<span class=badge title=\\""+esc(st.label)+"\\">"+(st.mark||st.icon)+"</span>"+',
  '        "<div class=main><div class=title>"+esc(t.title)+"</div>"+',
  '        (sub?"<div class=sub>"+sub+"</div>":"")+"</div>"+',
  '        "<span class=when>"+ageShort(now-t.last_seen)+"</span></div>";',
  '    }',
  '    return "<div class=\\"task"+(guess?" guess":"")+(unread?" unread":"")+"\\" data-id=\\""+esc(t.id)+"\\" style=\\"--bar:"+st.color+"\\">"+',
  '      "<span class=dot></span>"+',
  '      "<span class=\\"badge"+(t.state==="waiting"?" pulse":"")+"\\">"+st.icon+" "+esc(st.label)+"</span>"+',
  '      "<div class=main><div class=title>"+esc(t.title)+"</div>"+',
  '      ((t.summary||t.prompt)?"<div class=summary>"+esc(t.summary||t.prompt)+"</div>":"")+',
  '      "<div class=meta><span>"+esc(t.agent)+(guess?" (推测)":"")+"</span>"+',
  '      (bgN?"<span style=\'color:#06b6d4\'>⏳ "+bgN+" 个后台任务在跑</span>":"")+',
  '      (t.cwd?"<code>"+esc(shortCwd(t.cwd))+"</code>":"")+',
  '      "<span>"+age(now-t.last_seen)+"前</span></div></div></div>";',
  '  }).join("") + (hidden?"<button id=more class=more>还有 "+hidden+" 条更早的"+(hiddenUnread?"（"+hiddenUnread+" 条没看过）":"")+"</button>"',
  '    : window.__expanded?"<button id=more class=more>收起更早的</button>":"");',
  '  var mb=document.getElementById("more");',
  '  if(mb)mb.onclick=function(){window.__expanded=!window.__expanded;render(tasks);};',
  '  document.title=(need.length?"("+need.length+") ":"")+"agentdesk";',
  '  var top=need.length?(STATES[need[0].state]||{}).color:"#10b981";',
  '  setFavicon(top||"#10b981",need.length);',
  '  var unreadN=tasks.filter(function(t){return t.state==="done"&&t.seen===false;}).length;',
  '  document.getElementById("allseen").style.display = unreadN? "inline-block" : "none";',
  '  var parts=[];',
  '  var act=need.length-unreadN;',
  // 340px 宽放不下完整句子，紧凑模式用短的，否则标题栏会被挤到换行
  '  if(COMPACT){',
  '    if(act>0) parts.push(act+" 等你");',
  '    if(unreadN) parts.push(unreadN+" 未看");',
  '    document.getElementById("count").textContent = parts.length? parts.join(" · ") : tasks.length+" 个 · 都不用管";',
  '  }else{',
  '    if(act>0) parts.push(act+" 个等你处理");',
  '    if(unreadN) parts.push(unreadN+" 个完成了还没看");',
  '    document.getElementById("count").textContent = parts.length? parts.join(" · ") : tasks.length+" 个任务 · 都不用管";',
  '  }',
  '}',

  // 声明放 notify 前面。var 提升让运行时不出错，但读代码的人不该靠这个
  'var reminded={}, REMIND_MS=90000;',
  'function notify(changed){',
  '  changed.forEach(function(t){',
  '    var st=STATES[t.state]; if(!st||st.notify==="never") return;',
  '    if(FG.indexOf(t.agent)>=0) return;   // 你正开着这个 agent 的窗口，别打扰',
  '    reminded[t.id]=Date.now();',
  '    if(t.state==="waiting") beep([880,1174]);',
  '    else if(t.state==="stale"||t.state==="failed") beep([660,550,440]);',
  '    var head=st.icon+" "+st.label+" · "+(t.title||t.agent);',
  '    var lines=[]; if(t.summary||t.prompt) lines.push(t.summary||t.prompt);',
  '    lines.push(t.agent+(t.cwd?"  ·  "+shortCwd(t.cwd):""));',
  '    try{',
  '      var n=new Notification(head,{body:lines.join("\\n"),tag:t.id,',
  '        requireInteraction: st.notify==="always"});',
  '      n.onclick=function(){window.focus();n.close();reminded[t.id]=Date.now()+600000;',
  '        if(t.seen===false) markSeen([t.id]);};   // 点了通知就是看到了这一条，精确',
  '    }catch(e){}',
  '  });',
  '}',

  // macOS 的横幅样式几秒就消失，一条通知很容易错过。
  // 所以没处理掉的任务会周期性重提醒，直到状态变化或你点掉。
  'function sweepReminders(){',
  '  if(!window.__last) return;',
  '  var now=Date.now();',
  '  var due=window.__last.filter(function(t){',
  '    if(ATT.indexOf(t.state)<0) return false;',
  '    return now-(reminded[t.id]||0) > REMIND_MS;',
  '  });',
  '  if(due.length) notify(due);',
  '  var live={}; (window.__last||[]).forEach(function(t){live[t.id]=1;});',
  '  Object.keys(reminded).forEach(function(k){if(!live[k]) delete reminded[k];});',
  '}',
  'setInterval(sweepReminders, 30000);',
  'function markSeen(ids){',
  '  if(!ids.length) return;',
  '  fetch("/api/seen",{method:"POST",headers:{"Content-Type":"application/json"},',
  '    body:JSON.stringify({ids:ids})});',
  '}',
  'document.getElementById("list").addEventListener("click",function(e){',
  '  var card=e.target.closest(".task.unread");',
  '  if(card) markSeen([card.getAttribute("data-id")]);',
  '});',
  'document.getElementById("allseen").onclick=function(){',
  '  var ids=(window.__last||[]).filter(function(t){return t.seen===false;}).map(function(t){return t.id;});',
  '  markSeen(ids);',
  '};',
  // 每次现查，不缓存 —— 壳注入 webkit 的时机不一定早于脚本执行，
  // 缓存一次的话赶不上就永远发不出消息
  'function shellMsg(){return window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.panel;}',
  'if(shellMsg()) document.body.classList.add("shell");',
  'setTimeout(function(){ if(shellMsg()) document.body.classList.add("shell"); },300);',
  'var folded=false;',
  // 窗口尺寸归壳管，网页只发意图；壳改完再回调 __setCollapsed 同步样式
  'window.__setCollapsed=function(on){',
  '  folded=!!on;',
  '  document.body.classList.toggle("folded",folded);',
  '  var b=document.getElementById("fold");',
  '  if(b){b.textContent=folded?"▸":"▾";b.title=folded?"展开":"收起";}',
  '};',
  'document.getElementById("fold").onclick=function(){',
  '  var mh=shellMsg(); if(!mh) return;',
  '  mh.postMessage({action: folded?"expand":"collapse"});',
  '};',
  'var es=new EventSource("/events");',
  'es.onmessage=function(e){var d=JSON.parse(e.data);',
  '  if(d.build){ if(BUILD && d.build!==BUILD){ location.reload(); return; } BUILD=d.build; }',
  '  if(d.states)STATES=d.states; if(d.attention)ATT=d.attention;',
  '  if(d.foreground)FG=d.foreground;',
  '  if(d.type==="foreground"){FG=d.agents||[];return;}',
  '  render(d.tasks||[]); notify(d.changed||[]);};',
  'setInterval(function(){ if(window.__last) render(window.__last); },30000);',
  'var _r=render; render=function(t){window.__last=t;_r(t);};',
].join('\n');
